/** @type {import('tailwindcss').Config} */
export default {
            darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
            theme: {
                extend: {
                    "colors": {
                        "on-primary-container": "#90b5ff",
                        "on-secondary-container": "#04723d",
                        "inverse-on-surface": "#f0f1f2",
                        "surface-container-lowest": "#ffffff",
                        "tertiary-fixed": "#dee3eb",
                        "primary-fixed": "#d8e2ff",
                        "tertiary-container": "#42474e",
                        "primary-container": "#004492",
                        "on-tertiary-container": "#b1b5bd",
                        "on-primary-fixed": "#001a40",
                        "secondary": "#006d3a",
                        "on-tertiary-fixed-variant": "#42474e",
                        "outline-variant": "#c3c6d3",
                        "inverse-surface": "#2e3132",
                        "secondary-container": "#97f3b2",
                        "surface-bright": "#f8f9fa",
                        "on-tertiary": "#ffffff",
                        "error": "#ba1a1a",
                        "on-surface": "#191c1d",
                        "surface-container-highest": "#e1e3e4",
                        "surface-container": "#edeeef",
                        "surface-tint": "#2b5dac",
                        "tertiary-fixed-dim": "#c2c7cf",
                        "outline": "#737782",
                        "on-secondary-fixed-variant": "#00522a",
                        "surface-container-low": "#f3f4f5",
                        "primary-fixed-dim": "#acc7ff",
                        "secondary-fixed": "#9af6b5",
                        "surface-dim": "#d9dadb",
                        "on-primary": "#ffffff",
                        "background": "#f8f9fa",
                        "on-secondary": "#ffffff",
                        "surface-container-high": "#e7e8e9",
                        "tertiary": "#2c3137",
                        "error-container": "#ffdad6",
                        "on-error": "#ffffff",
                        "on-primary-fixed-variant": "#004492",
                        "secondary-fixed-dim": "#7eda9a",
                        "on-secondary-fixed": "#00210e",
                        "on-error-container": "#93000a",
                        "surface-variant": "#e1e3e4",
                        "inverse-primary": "#acc7ff",
                        "on-surface-variant": "#434751",
                        "on-tertiary-fixed": "#171c22",
                        "surface": "#f8f9fa",
                        "primary": "#002e68",
                        "on-background": "#191c1d"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.25rem",
                        "xl": "0.5rem",
                        "full": "0.75rem"
                    },
                    "spacing": {
                        "base": "8px",
                        "stack-md": "24px",
                        "container-max": "1200px",
                        "margin-mobile": "16px",
                        "stack-sm": "8px",
                        "gutter": "24px",
                        "stack-lg": "48px"
                    },
                    "fontFamily": {
                        "body-md": ["Lexend"],
                        "label-caps": ["Public Sans"],
                        "h3": ["Public Sans"],
                        "body-lg": ["Lexend"],
                        "h2": ["Public Sans"],
                        "h1": ["Public Sans"]
                    },
                    "fontSize": {
                        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
                        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "700"}],
                        "h3": ["24px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
                        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
                        "h2": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
                    }
                },
            },
        };
